#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

supported_arch_list=( "$@" )
current_arch="$(dpkg --print-architecture)"

for supported_arch in "${supported_arch_list[@]}"; do
  if [ "${current_arch}" = "${supported_arch}" ]; then
    exit 0
  fi
done

printf '%s' "Unavailable on ${current_arch}."
exit 1
